### ISSUE TITLE
v1.10.29版本页面显示“找不到页面”

### ISSUE THREAD

**Issue by bevis-canway** [TencentBlueKing/bk-iam-saas#2764]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
saas 1.10.29  , 后台 1.12.14

**发生了什么(What happened):**
所有页面显示“没有找到页面”，权限中心不可用
![image](https://github.com/user-attachments/assets/1693f3b5-ac62-4ee8-b3fc-37fa1d4b0e38)

**期望是什么(What you expected to happen):**
正常使用

**如何复现(How to reproduce it):**
部署后打开页面就是

**相关的日志详情(SaaS 及后台日志说明 https://bk.tencent.com/docs/document/6.0/160/8398)和截图等(Log & Screenshot):**
接口报错：
![image](https://github.com/user-attachments/assets/22d1b74e-31e0-4ae4-a533-05d9bec5edaf)
![image](https://github.com/user-attachments/assets/43ac4adc-d243-427a-9802-0e8f42bff6dc)

saas日志：

![image](https://github.com/user-attachments/assets/a80d5088-4ded-4e34-9a3c-7e4f006bd92a)
`[root@build-47 bk_iam]# tail -10f bk_iam.log
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
ERROR [2024-08-06 15:03:03] ./backend/api/authentication.py 76 _decode_jwt 1194 139654084249728 
         9bc6713a78c04343b9ff07effcc7b919       decode jwt fail, jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiIsImtpZCI6ImFwaWd3IiwiaWF0IjoxNzIyOTI3NzgzfQ.eyJhcHAiOnsidmVyc2lvbiI6MSwiYmtfYXBwX2NvZGUiOiJia19zb3BzIiwidmVyaWZpZWQiOnRydWV9LCJ1c2VyIjp7InZlcnNpb24iOjEsImJrX3VzZXJuYW1lIjoiYWRtaW4iLCJ2ZXJpZmllZCI6ZmFsc2V9LCJpc3MiOiJBUElHVyIsIm5iZiI6MTcyMjkyNzQ4MywiZXhwIjoxNzIyOTI4NjgzfQ.CJQFbJfp3D1fpetk-z-uKefKa0Pv3ssfIBKk_FD4yNL8BZ6XGhGWdNh3xhkHUXkp6m8_zU-5OK6nSfGkspLwknmYQ38khM4pm9oiV8pEZV8Xsqp5ZJ7YmFjKxDcq7WWbYt-e3cV8flsrpANhUiv_WUPZ7psYAkQxs-gSsrBrpJCUktRCePy5rvnzUg1lTLeOTMX-9hTFNsGYb6AEg7hNa_Nv8MC0pMHOLuIUexmNADRs5-ISX-bS8lLZmPxnnS1Jf60qtq9MeXec0_eTKLjEJbfE5m2QZBDN106V3zaK2SVFEXuU-RCJhXB3thHLNs9X2wA1j4myZLnq8y_vf3JG_w 
Traceback (most recent call last):
  File "./backend/api/authentication.py", line 74, in _decode_jwt
  File "/cache/.bk/env/lib/python3.6/site-packages/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/cache/.bk/env/lib/python3.6/site-packages/jwt/api_jwt.py", line 97, in decode_complete
    'It is required that you pass in a value for the "algorithms" argument when calling decode().'
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
`
**备注(Anything else we need to know):**

**Comment by bevis-canway** [comment]
修复版本1.10.33.前端路由问题
