### ISSUE TITLE
[SaaS] 优化: 组织架构同步记录日志展示换行

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#374]
当前展示日志没有换行

```
sync_organization error
Traceback (most recent call last): File "/data/home/bk/bk_iam/env/py36/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) File "/data/home/bk/bk_iam/env/py36/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute return self.cursor.execute(query, args) File "/data/home/bk/bk_iam/env/py36/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute res = self._query(query) File "/data/home/bk/bk_iam/env/py36/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query db.query(q) File "/data/home/bk/bk_iam/env/py36/lib64/python3.6/site-packages/MySQLdb/connections.py", line 259, in query _mysql.connection.query(self, query) MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'xxxxx' for key 'username'") The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/data/home/bk/bk_iam/dist/iam_app/backend/apps/organization/tasks.py", line 79, in sync_organization service.sync_to_db() File "/data/home/bk/bk_iam/dist/iam_app/backend/biz/org_sync/user.py", line 99, in sync_to_db self.created_handler() File "/data/home/bk/bk_iam/dist/iam_app/backend/biz/org_sync/user.py", line 55, in created_handler User.objects.bulk_create(created_users, batch_size=1000) File "/data/home/bk/bk_iam/env/py36/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method return getattr(self.get_queryset(), name)(*args, **kwargs) File "/data/home/bk/bk_iam/env/py36/lib/python3.6/site-packages/django/db/models/query.py", line 468, in bulk_create self._batched_insert(objs_with_pk, fields, batch_size, ignore_conflicts=ignore_conflicts) File "/data/home/bk/bk_iam/env/py36/lib/python3.6/site-packages/django/db/models/query.py", line 1211, in _batched_insert self._insert(item, fields=fields, using=self.db, ignore_conflicts=ignore_conflicts) File "/data/home/bk/bk_iam/env/py36/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert return query.get_compiler(using=using).execute_sql(return_id) File "/data/home/bk/bk_iam/env/py36/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql cursor.execute(sql, params) File "/data/home/bk/bk_iam/env/py36/lib/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute return super().execute(sql, params) File "/data/home/bk/bk_iam/env/py36/lib/python3.6/site-packages/raven/contrib/django/client.py", line 123, in execute return real_execute(self, sql, params) File "/data/home/bk/bk_iam/env/py36/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute return self._execute_with_wrappers(sql, params, many=False, executor=self._execute) File "/data/home/bk/bk_iam/env/py36/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers return executor(sql, params, many, context) File "/data/home/bk/bk_iam/env/py36/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) File "/data/home/bk/bk_iam/env/py36/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__ raise dj_exc_value.with_traceback(traceback) from exc_value File "/data/home/bk/bk_iam/env/py36/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) File "/data/home/bk/bk_iam/env/py36/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute return self.cursor.execute(query, args) File "/data/home/bk/bk_iam/env/py36/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute res = self._query(query) File "/data/home/bk/bk_iam/env/py36/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query db.query(q) File "/data/home/bk/bk_iam/env/py36/lib64/python3.6/site-packages/MySQLdb/connections.py", line 259, in query _mysql.connection.query(self, query) django.db.utils.IntegrityError: (1062, "Duplicate entry 'xxxxx' for key 'username'")
```

**Comment by huangpeng0428** [comment]
麻烦贴一下需要优化的日志链接

**Comment by huangpeng0428** [comment]
done
